import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "my-app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="style.css" />
      </head>
      <body 
      className={inter.className}>{children}
     <script src="commonjs"></script>
      </body>
    </html>
  );
}
